### PR TITLE
Update fastdds-suite-2.11.x dependencies

### PR DESCRIPTION
**Pull request by richiprosima**
Update fastdds-suite-2.11.x dependencies:
* fastdds,v2.11.3;fastdds_python,v1.2.3;shapes-demo,v2.11.3

### CODE REVIEW

**Comment by elianalf** [comment]
@richiprosima please test this

**Comment by elianalf** [comment]
@richiprosima please test this

**Comment by elianalf** [comment]
CI passed locally. Ready to merge!

**Comment by elianalf** [comment]
CI passed locally. Ready to merge!

**Review by EduPonz — APPROVED** [review]

**Pull request merged**
