### PR TITLE
[17830] Pass branch to tracker script

### PR DESCRIPTION
**Pull request by EduPonz**
This PR fixes the update dependencies job.

### CODE REVIEW

**Review by JLBuenoLopez — APPROVED** [review]
LGTM

**Comment by JLBuenoLopez** [comment]
Does the CI error has something to do with the changes in the script?

```
15:37:40 dds_suite_ci.bash: line 1: syntax error near unexpected token `newline'
15:37:40 dds_suite_ci.bash: line 1: `<!DOCTYPE html>'
```

**Comment by EduPonz** [comment]
@richiprosima please test this

**Comment by EduPonz** [comment]
@richiprosima please test this

**Pull request merged**
